name: colony_counting
channels:
  - anaconda
  - conda-forge
dependencies:
  - numpy=1.24.4=py311hb8f3215_0
  - scikit-learn=1.3.0=py311h7aedaa7_0
  - matplotlib=3.8.2=py311ha1ab1f8_0
  - pillow=10.2.0=py311hb9c5795_0
